name: flutter_cached
description: "🧾 Flutter widget allowing cache-based data display featuring swipe-to-refresh and an error banner."
version: 2.0.2
author: Marcel <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/cached_listview

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^1.5.6
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
