name: flutter_cached
description: "🧾 Flutter widget allowing easy cache-based data display in a ListView featuring pull-to-refresh and error banners."
version: 2.0.1
author: Marcel <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/cached_listview

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^1.5.6
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
